/**
 * Demo: Anfrage Component Usage Examples
 *
 * This demonstrates the NEW Anfrage/EmailModal component with automatic
 * inquiry number generation based on requirements in prompts/anfrage.md
 *
 * The EmailModal now handles:
 * - Automatic inquiry number generation (format: #YYYYMMDD-HHMMSS)
 * - Subject line building: <title> <text> #<quotenr>
 */

import { useState } from 'react';
import EmailModal from '../src/EmailModal';

// Example 1: CAD Configurator with Article Number
export const CadConfiguratorExample = () => {
  const [showModal, setShowModal] = useState(false);

  const articleNumber = "ART-12345";

  return (
    <div>
      <h2>Example 1: CAD Configurator</h2>
      <button onClick={() => setShowModal(true)}>
        CAD {/* For CAD configurator, button shows "CAD" */}
      </button>

      <p>Subject will be: <code>CAD Artnr: 12345 #20251026-143052</code></p>
      <p className="text-sm text-gray-600">
        (Inquiry number is auto-generated by EmailModal)
      </p>

      {showModal && (
        <EmailModal
          title="CAD"
          subtitle="Bitte füllen Sie die Kontaktinformationen aus"
          emailTo="sales@syskomp-group.com"
          subjectText={`Artnr: ${articleNumber}`}
          bodyWithoutContact={`Ich interessiere mich für:\n\nArtikel: ${articleNumber}\n\nBitte senden Sie mir ein Angebot.`}
          onClose={() => setShowModal(false)}
        />
      )}
    </div>
  );
};

// Example 2: Rollenförderer (Bill of Materials)
export const RollenfoerdererExample = () => {
  const [showModal, setShowModal] = useState(false);

  return (
    <div>
      <h2>Example 2: Rollenförderer (Stückliste)</h2>
      <button onClick={() => setShowModal(true)}>
        Angebot
      </button>

      <p>Subject will be: <code>Angebot Rollenförderer #20251026-143052</code></p>
      <p className="text-sm text-gray-600">
        (Inquiry number is auto-generated by EmailModal)
      </p>

      {showModal && (
        <EmailModal
          title="Angebot"
          emailTo="sales@syskomp-group.com"
          subjectText="Rollenförderer"
          bodyWithoutContact="Ich interessiere mich für einen Rollenförderer.\n\nBitte senden Sie mir ein Angebot."
          onClose={() => setShowModal(false)}
        />
      )}
    </div>
  );
};

// Example 3: KLT-Lifter Configuration
export const KltLifterExample = () => {
  const [showModal, setShowModal] = useState(false);

  const articleNumber = "KLT-LIFT-001";

  return (
    <div>
      <h2>Example 3: KLT-Lifter Configurator</h2>
      <button onClick={() => setShowModal(true)}>
        Angebot
      </button>

      <p>Subject will be: <code>Angebot KLT-Lifter Konfiguration - Art.-Nr.: KLT-LIFT-001 #20251026-143052</code></p>
      <p className="text-sm text-gray-600">
        (Inquiry number is auto-generated by EmailModal)
      </p>

      {showModal && (
        <EmailModal
          title="Angebot"
          emailTo="sales@syskomp-group.com"
          subjectText={`KLT-Lifter Konfiguration - Art.-Nr.: ${articleNumber}`}
          bodyWithoutContact={`Konfiguration:\n\nProdukt: KLT-Lifter\nArtikel: ${articleNumber}\n\nTechnische Details:\n- Hubhöhe: 1500mm\n- Tragkraft: 100kg\n\nBitte senden Sie mir ein Angebot.`}
          onClose={() => setShowModal(false)}
        />
      )}
    </div>
  );
};

// Demo App showing all examples
export const AnfrageDemo = () => {
  return (
    <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}>
      <h1>Anfrage Component - Demo Examples</h1>

      <div style={{ marginBottom: '40px', padding: '15px', background: '#f5f5f5', borderRadius: '5px' }}>
        <h3>✅ Implemented Requirements (from prompts/anfrage.md)</h3>
        <ul>
          <li><strong>Subject Structure:</strong> &lt;title&gt; &lt;text kommt vom Modul&gt; #&lt;quotenr&gt;</li>
          <li><strong>Quote Number Format:</strong> #YYYYMMDD-HHMMSS (automatically generated by EmailModal)</li>
          <li><strong>Title is a parameter:</strong>
            <ul>
              <li>For CAD configurators: title = "CAD"</li>
              <li>For Stückliste/others: title = "Angebot"</li>
            </ul>
          </li>
          <li><strong>Context-specific text:</strong>
            <ul>
              <li>For CAD configurators: "Artnr: [number]"</li>
              <li>For Stückliste: "Rollenförderer"</li>
            </ul>
          </li>
        </ul>
        <div style={{ marginTop: '15px', padding: '10px', background: '#e7f3ff', borderLeft: '4px solid #007bff', borderRadius: '4px' }}>
          <strong>New EmailModal API:</strong>
          <p style={{ margin: '5px 0 0 0', fontSize: '14px' }}>
            Set the modal <code>title</code> (varies by use case: "CAD" for configurators, "Angebot" for Stückliste) and <code>subjectText</code> (e.g., "Artnr: 12345", "Rollenförderer").
            The <code>title</code> will be used for both the modal header AND the subject line.
            EmailModal will automatically generate the inquiry number and format the subject line as: <code>title + subjectText + #quotenr</code>
          </p>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
        <CadConfiguratorExample />
        <RollenfoerdererExample />
        <KltLifterExample />
      </div>
    </div>
  );
};

export default AnfrageDemo;
